### PR TITLE
C-H arylation dataset submission

### PR DESCRIPTION
**Pull request by beef-broccoli**
Dataset of a pd-catalyzed C-H arylation reaction with various aryl bromides, imidazoles and ligands. 

Associated with [publication](https://chemrxiv.org/engage/chemrxiv/article-details/64c7e2e1658ec5f7e5808425), Fig. 4 and related texts in the manuscript. Experimental details can be found in SI Section 9.

Reaction template, result spreadsheet and dataset pbtxt files are also included. 
[submission 08-18-23.zip](https://github.com/open-reaction-database/ord-data/files/12384008/submission.08-18-23.zip)

### CODE REVIEW

**Comment by beef-broccoli** [comment]
hmmm, so one of the checks says all reactions have the same ID, which i can verify is true (all of them has the same ID ord-c2e0e8e7b99b4eb8b2894520507ed3a0). Is it something simple that i missed? Does the spreadsheet need an index column?

**Comment by connorcoley** [comment]
I believe this should be fixed if you omit the `reaction_id` from the Reaction template before the enumeration. This is something that we should have the enumeration script check for in the future, but would you mind redoing the enumeration for this submission?

**Comment by beef-broccoli** [comment]
Also not sure whether the descriptions were included. If you need a name and description: 
name: Pd-catalyzed C-H arylation of imidazole with aryl bromide
description: palladium-catalyzed imidazole C5-H arylation reactivities with 8 aryl bromides and 8 imidazoles are evaluated with 24 monophosphine ligands.

**Comment by connorcoley** [comment]
Thanks! 

The name and description can be added by inserting two lines at the beginning of the dataset pbtxt, see attached

[dataset.pbtxt.zip](https://github.com/open-reaction-database/ord-data/files/12423587/dataset.pbtxt.zip)

A few questions to double-check some minor points. I'm looking at Fig 4 of the preprint, so apologies if this is wrong:
- The aryl bromide is listed as 20 umol in 40 uL DMA as the limiting reactant. KOPiv is drawn in the figure as 3 equiv with an amount per reaction of 45 umol. The imidazole is 40 umol 2 equiv). Is KOPiv supposed to be 60 umol or is Figure 4 different from these reactions? The ligand is 1 umol (5%) and precatalyst 0.45 umol (2.25%) which both check out. It's only the KOPiv quantity that I'm not sure about
- Would you be okay replacing the CUSTOM workup ("dilute to 900 microliter with DMA") with an addition operation so that the structure of DMA and its volume can be defined in a structured way?
- The FILTRATION workup step includes rinsing with 400 uL ACN/water; this could be separated into a FILTRATION step and then a WASH step; in the WASH step, the exact composition of what is added can be defined in a structured way
- The `details` field of a SMILES or NAME compound identifier isn't totally necessary (currently used for the ligand component) and could be removed
- I'm lukewarm about `NAME` identifiers for compounds that refer to generic classes (e.g., "aryl bromide substrate", "imidazole substrate") rather than the name of the compound itself. It's okay to leave it in though!

If you are pressed for time, feel free to simply clarify the KOPiv quantity and I can make the changes to the rest of the template.

**Comment by beef-broccoli** [comment]
Thanks for your feedback!

1. The discrepancy in reagent amounts are fixed. Base amount was right, so is the equivalents in Fig.4.  i forgot that after all the reagents are added, only 150ul out of 200 ul was added to the base plate. A ligand plate was also used so there shouldn't be any solvent or stock solution associated with that, this was also fixed.
2. Workup changed to addition.
3. changed to two separate steps: filter and wash
4. details were removed for ligands
5. i agree, they are redundant especially since input names are already defined for them
6. Name and description was also added for the dataset 

[submission 08-27-23.zip](https://github.com/open-reaction-database/ord-data/files/12448576/submission.08-27-23.zip)

**Comment by beef-broccoli** [comment]
Somehow the enumeration (or maybe from the template) generated an empty "name" identifier for each reaction that throws an error when checked by submission script. This was fixed. 

[submission 08-27-23.zip](https://github.com/open-reaction-database/ord-data/files/12448596/submission.08-27-23.zip)

**Comment by beef-broccoli** [comment]
Sorry! it was my fault. Forgot to add it in. 

[submission 08-28-23.zip](https://github.com/open-reaction-database/ord-data/files/12479311/submission.08-28-23.zip)

**Pull request merged**
