### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by eisbr094**

### CODE REVIEW

**Comment by skearnes** [comment]
Hi @eisbr094, thanks for your submission! Could you please remove the *.xlsx files from the commit and attach them to a comment on the pull request instead?

**Comment by skearnes** [comment]
> Hi @eisbr094, thanks for your submission! Could you please remove the *.xlsx files from the commit and attach them to a comment on the pull request instead?

Actually, I can take care of this as part of my review.

**Comment by eisbr094** [comment]
Hi @skearnes - just to confirm no action is needed on my part? I also made a small typo with the number - should be 384 reactions not 382. Thank you for your assistance -Eric

**Comment by skearnes** [comment]
> Hi @skearnes - just to confirm no action is needed on my part? I also made a small typo with the number - should be 384 reactions not 382. Thank you for your assistance -Eric

Right, no action needed now. Will hopefully get to this in the next few days.

**Comment by skearnes** [comment]
Attaching the *.xlsx files here:

[Vinyl ether plate ORD.xlsx](https://github.com/open-reaction-database/ord-data/files/11713493/Vinyl.ether.plate.ORD.xlsx)
[Styrene plate ORD.xlsx](https://github.com/open-reaction-database/ord-data/files/11713494/Styrene.plate.ORD.xlsx)
[Octene plate ORD.xlsx](https://github.com/open-reaction-database/ord-data/files/11713495/Octene.plate.ORD.xlsx)
[N-vinylpyrrolidone ORD.xlsx](https://github.com/open-reaction-database/ord-data/files/11713496/N-vinylpyrrolidone.ORD.xlsx)

**Comment by skearnes** [comment]
@eisbr094 can you please attach (in a comment) the reaction template pbtxt that you used for each dataset? I'm going to merge this so I can edit some minor things in the files so the tests will run.

**Comment by skearnes** [comment]
@eisbr094 could you also please update the description of this PR to include a high-level description of the data? I'll use that to update the dataset metadata that gets stored in the database via #168.

**Comment by eisbr094** [comment]
Hi @skearnes - here are the .txts for all 4 plates. I was unable to attach .pbtxt with GitHub. Can also attach to an email if you would prefer.
[Vinyl ether plate ORD_dataset (2) (1).txt](https://github.com/open-reaction-database/ord-data/files/11713521/Vinyl.ether.plate.ORD_dataset.2.1.txt)
[Styrene plate ORD_dataset (2) (1).txt](https://github.com/open-reaction-database/ord-data/files/11713522/Styrene.plate.ORD_dataset.2.1.txt)
[Octene plate ORD_dataset (2) (1).txt](https://github.com/open-reaction-database/ord-data/files/11713523/Octene.plate.ORD_dataset.2.1.txt)
[N-vinylpyrrolidone ORD_dataset (1) (1).txt](https://github.com/open-reaction-database/ord-data/files/11713524/N-vinylpyrrolidone.ORD_dataset.1.1.txt)

**Comment by skearnes** [comment]
> Hi @skearnes - here are the .txts for all 4 plates. I was unable to attach .pbtxt with GitHub. Can also attach to an email if you would prefer. [Vinyl ether plate ORD_dataset (2) (1).txt](https://github.com/open-reaction-database/ord-data/files/11713521/Vinyl.ether.plate.ORD_dataset.2.1.txt) [Styrene plate ORD_dataset (2) (1).txt](https://github.com/open-reaction-database/ord-data/files/11713522/Styrene.plate.ORD_dataset.2.1.txt) [Octene plate ORD_dataset (2) (1).txt](https://github.com/open-reaction-database/ord-data/files/11713523/Octene.plate.ORD_dataset.2.1.txt) [N-vinylpyrrolidone ORD_dataset (1) (1).txt](https://github.com/open-reaction-database/ord-data/files/11713524/N-vinylpyrrolidone.ORD_dataset.1.1.txt)

Thanks; these work fine. In the future you can upload a zip or tar containing the raw pbtxt without having to rename them.

**Comment by skearnes** [comment]
> Hi @skearnes - here are the .txts for all 4 plates. I was unable to attach .pbtxt with GitHub. Can also attach to an email if you would prefer. [Vinyl ether plate ORD_dataset (2) (1).txt](https://github.com/open-reaction-database/ord-data/files/11713521/Vinyl.ether.plate.ORD_dataset.2.1.txt) [Styrene plate ORD_dataset (2) (1).txt](https://github.com/open-reaction-database/ord-data/files/11713522/Styrene.plate.ORD_dataset.2.1.txt) [Octene plate ORD_dataset (2) (1).txt](https://github.com/open-reaction-database/ord-data/files/11713523/Octene.plate.ORD_dataset.2.1.txt) [N-vinylpyrrolidone ORD_dataset (1) (1).txt](https://github.com/open-reaction-database/ord-data/files/11713524/N-vinylpyrrolidone.ORD_dataset.1.1.txt)

Oh I'm actually looking for the short pbtxt template with the `$` annotations that you coupled with the spreadsheets? You can upload the lot as a zip/tar to avoid the github file extension issues.

**Comment by eisbr094** [comment]
Hi @skearnes - here are the zipped templates. With respect to high level details for the PR - where should I do this? Thanks -Eric 
[EI pbtxts.zip](https://github.com/open-reaction-database/ord-data/files/11713535/EI.pbtxts.zip)

**Comment by skearnes** [comment]
> Hi @skearnes - here are the zipped templates. With respect to high level details for the PR - where should I do this? Thanks -Eric [EI pbtxts.zip](https://github.com/open-reaction-database/ord-data/files/11713535/EI.pbtxts.zip)

Thanks; you can either add a new comment here or edit the PR description at the top.

**Comment by eisbr094** [comment]
Thank you - I have updated the title. Is this level of detail appropriate?

Thanks for all your help,
Eric

**Comment by skearnes** [comment]
Great, thanks!

**Comment by skearnes** [comment]
@eisbr094 I'm going to make two additional changes based on the ord-help@ thread:
* I'm removing KOtBu entries where the amount added was zero
* I'm renaming the changed GC-FID analysis to GC-FID (slow) so there is a distinction in the analysis name as well as the description

Does that sound good to you?

**Comment by skearnes** [comment]
> @eisbr094 I'm going to make two additional changes based on the ord-help@ thread:
> 
> * I'm removing KOtBu entries where the amount added was zero
> * I'm renaming the changed GC-FID analysis to GC-FID (slow) so there is a distinction in the analysis name as well as the description
> 
> Does that sound good to you?

* I found 352 zero-valued amounts (expected since you said there were 8 non-zero per plate)
* I found 192 analyses where the "special" GC-FID method was used---should that have only affected one plate?

**Comment by eisbr094** [comment]
@skearnes sounds good for removing KOtBu where not applicable - makes sense that there were 352  non there.
There should only be one plate (96 reactions) with the special GC-FID method was used (octene).The remaining plates were analyzed as normal. I realized there was a typo in the styrene plate. The fixed .pbtxt is here: 
[styrene plate.zip](https://github.com/open-reaction-database/ord-data/files/11725137/styrene.plate.zip)

Sorry about that!

Eric

**Comment by skearnes** [comment]
Thanks!

**Pull request merged**
