### PR TITLE
upload new data

### PR DESCRIPTION
**Pull request by beef-broccoli**
Ni-catalyzed Suzuki cross coupling dataset (Doyle, Sigman, Merck)
Section 3 of SI contain details on the reactions
https://doi.org/10.26434/chemrxiv.14388557.v1

### CODE REVIEW

**Comment by beef-broccoli** [comment]
also attaching template and raw data here
[template+raw.zip](https://github.com/open-reaction-database/ord-data/files/6643496/template%2Braw.zip)

**Comment by connorcoley** [comment]
Thanks @beef-broccoli !

Template file:
- K3PO4 solution input looks good
- Catalyst solution input looks good
- From the SI, the quantity of the aryl chloride seems to be 7.92 but 8.0 micromole is probably within the precision of that measurement
- Boronic acid solution looks good (using molarity of water, 40 micromole seems approximate but good)
- Procedure, setup, conditions, workup all look excellent. I find it reasonable that you've specified the internal standard input and its structure explicitly, but have omitted the messy details of that final dilution workup step.

Spreadsheet file
- The spreadsheet doesn't align with the table in the SI, which makes it a little hard to check everything 100%. However, I mainly focused on doing some spot checks of SMILES strings and structures. All of the reactants and products look good, and I could match up a few of the specific yield% values between the spreadsheet and table.
- I won't check all of the ligand structures, but I imagine that the team knows how to handle its phosphine ligands :)
- It might be nice to have a ligand _name_ column in the spreadsheet to include that in the enumeration, just for human-legibility, but all of this information looks great. I will leave it up to you if you would like to add a ligand name identifier (and column) to the enumeration to re-submit the dataset, otherwise feel free to merge this in to the branch once all of the checks pass

**Review by connorcoley — APPROVED** [review]

**Comment by beef-broccoli** [comment]
@connorcoley Thanks! I will add the ligand names and upload the spreadsheet I used to do enumeration.

**Comment by beef-broccoli** [comment]
[template+data.zip](https://github.com/open-reaction-database/ord-data/files/6659195/template%2Bdata.zip)
also uploading new template and spreadsheet used for enumeration here, just to keep a record

**Comment by beef-broccoli** [comment]
Also don't think I have write access to merge :(

**Comment by connorcoley** [comment]
This looks great! And oops sorry for the poor directions then; I'll merge this in. Thanks again!

**Pull request merged**
