### PR TITLE
Uploading dataset pbtxt for 24Golden paper Fig 7

### PR DESCRIPTION
**Pull request by spencerheins**
This is an enumerated dataset of 288 reactions from the paper https://doi.org/10.1016/j.chempr.2024.04.001 (Figure 7) created using the interactive web editor. Template reaction pbtxt and css are attached.

[Archive.zip](https://github.com/user-attachments/files/16415637/Archive.zip)

### CODE REVIEW

**Comment by bdeadman** [comment]
Thanks @spencerheins. I'll review this and get back to you tonight or tomorrow.

**Comment by bdeadman** [comment]
Hi @spencerheins
This is a well put together dataset. I've made a few minor changes (see attached) which I will summarise below. Please move the replacement dataset to inside the data folder and I can then approve the merge.

[spencerheins.zip](https://github.com/user-attachments/files/16433259/spencerheins.zip)

Changes made:
- Elaborated the dataset description
- Added the well identifier to reactions
- added some 'details' to the reaction identifiers and the product LC measurement to give context.
- changed the provenance html to point to the doi link (should be more permanent)

Note that I couldn't access the paper or the SI since they are behind a paywall. The dataset is however consistent with the abstract and my general synthesis knowledge. If you want me to provide a more thorough check then please send me (by email) a copy of the paper and/or SI for reference.

**Comment by spencerheins** [comment]
Hi @bdeadman,

Thanks for reviewing the data. Your changes sound good to me. Can you clarify what you mean by moving the replacement dataset to inside the data folder? I am unsure how to do this. Is this another pull request, or do I place the zip file into the data folder under this new branch? 

Also, the paper and SI are attached now if you would like to take a closer look:
[24Chem Golden.zip](https://github.com/user-attachments/files/16434255/24Chem.Golden.zip)

Thank you!
Spencer

**Comment by bdeadman** [comment]
Hi @spencerheins. You need to move the .pbtxt dataset file into the ord-data/data folder. The rest of the contents in the zipped folder do not get included in the ord-data repo, but we include them in the pull request commentary here.

I'm a bit unsure what happens if you move this file while you have this pull request open. Once the new dataset is in, and the old dataset out, that commit will show up in your GitHub account and I think you should be able to pull it through as an update to this pull request. If it helps we can have a quick call to solve it together.

Alternatively,  you or I can cancel this pull request, and make a new branch and pull request. If you are busy I can get it done from my fork of ord-data, or if you give me some edit rights on your ord-data fork then I could help pull it through from there.

Also, can you please edit your comment above to remove the folder with the paper and SI. I've got it now, but we probably shouldn't store a copy of copyrighted material here in a public forum.

**Comment by bdeadman** [comment]
@spencerheins don't worry about the paper and SI. I was able to remove it from my account.

**Comment by skearnes** [comment]
Moving files around is fine, and it doesn't matter which folder you put a
new dataset in: everything is diffed against the main branch after each
commit.

**Comment by spencerheins** [comment]
@bdeadman  - the new .pbtxt file has been deposited into the ord-data/data folder in the spencerheins:24Golden_Fig7_submission branch and a pull request created. Please let me know if this is correct (or not).

Thank you.

**Comment by bdeadman** [comment]
@spencerheins I can confirm that the new .pbtxt file is in this pull request. We'll need you to delete your [old dataset file](https://github.com/spencerheins/ord-data/blob/24Golden_Fig7_submission/24_Golden_Fig_7_dataset.pbtxt) as well.

**Comment by bdeadman** [comment]
No problem @spencerheins we want your data so assistance is limitless!

However, I can still see the dataset in your branch. I think it may not have been committed after you deleted the file. I expect the [commit list](https://github.com/open-reaction-database/ord-data/pull/194/commits) to show a 3rd entry when this change is committed.

**Review by bdeadman — APPROVED** [review]
Requested changes have been made. Approved for merge.

**Comment by bdeadman** [comment]
Thanks @spencerheins. The dataset has been merged into a branch on ORD, and is now going through the automated workflows to prepare it for merge into main. You can follow the progress on #197.

Once the dataset is in the main branch, we'll still wait until it appears in the online browser. At that point we'll announce it on LinkedIn.

**Comment by spencerheins** [comment]
Great to hear! Will "#197" be the official ORD submission number?

**Comment by bdeadman** [comment]
Depends how you want to use 'submission number'. A more appropriate label might be the dataset id and location which will be data/a1/ord_dataset-a12fa15d036d489c971b0b514caeae52.pb.gz

**Comment by spencerheins** [comment]
@bdeadman - we have discovered some errors in this dataset. Some of the smiles strings for products and reactants do not match. I have a csv file with the correct strings. Can you please advise on how to correct this issue?

**Comment by skearnes** [comment]
@bdeadman @spencerheins you can edit the existing dataset and add an entry to the record_modified section in the schema.

**Comment by bdeadman** [comment]
[corrected template.zip](https://github.com/user-attachments/files/18097568/corrected.template.zip)
@spencerheins this zip has an updated template file with a record_modified entry (under your name) today. If you update the csv file for the whole dataset then you can run the enumeration again with this template. Make sure the columns names aren't changed (I've included the previous csv file for reference).

When it comes to making the new pull request, my instinct is to ensure the following:
- remember to add the dataset name and description back in to the new dataset file (it is not in the template)
- convert the file to the binary pb format (instead of readable pbtxt) and compress it with gzip
- name the file ord_dataset-a12fa15d036d489c971b0b514caeae52.pb.gz

The bottom two are to ensure that the automated workflows replace the existing dataset. I can take care of these though, just send me the new dataset in whatever format you have.

**Comment by spencerheins** [comment]
@bdeadman and @skearnes - here is the corrected dataset. (I was unable to upload the .pb.gz file and create a pull request myself.)

[ord_dataset-a12fa15d036d489c971b0b514caeae52.pb.gz](https://github.com/user-attachments/files/18099468/ord_dataset-a12fa15d036d489c971b0b514caeae52.pb.gz)

Thank you for the help making these corrections. Please let me know if there is anything else I need to do.

**Comment by bdeadman** [comment]
Confirmed the 'Reaction 1' label is an artifact from the template. No need for action from @spencerheins.

**Comment by spencerheins** [comment]
Sounds good @bdeadman , thank you!

**Comment by bdeadman** [comment]
@spencerheins I've realised the approach we used will replace all the reaction ids that have already been assigned to the dataset. I have a workflow in mind to update the file 'in place' if you can send me the csv file with the correct smiles strings.

**Comment by spencerheins** [comment]
@bdeadman - no problem. Here it is:
[Fig_7_data_corrected.csv](https://github.com/user-attachments/files/18113731/Fig_7_data_corrected.csv)

**Pull request merged**
