### PR TITLE
Uploading dataset for Barbas JACS 2009 Figure 1

### PR DESCRIPTION
**Pull request by wert0069**
Enumerated dataset from Barbas JACS 2009 Figure 1 used for Sigman analysis. 8 reactions.
[Barbas_Jacs_Figure1.zip](https://github.com/Open-Reaction-Database/ord-data/files/5531931/Barbas_Jacs_Figure1.zip)

### CODE REVIEW

**Comment by skearnes** [comment]
Thanks @wert0069! A few comments:

* Please move the "Solvent" input to be a second component of the catalyst input.
* I think the amount of catalyst should be 0.02 mmol instead of 0.1 mmol?
* Please leave `precision` undefined unless you have measured uncertainty values (rather than setting to zero).
* Please add `workup` steps representing the dilution, quench, extraction, and purification.
* Please indicate the `preparation` of the various inputs: several of the solvents were dried, and the catalysts and oxindoles were synthesized in-house.
* AFAICT there should be at least five `analysis` entries: `WEIGHT`, `LC` (HPLC), `HRMS`, `NMR_1H`, and `NMR_13C`. I would use the weight as the "yield analysis", the HPLC as the selectivity analysis (like you already have), and the others as "identity analysis" entries in the `product` section. Where appropriate, the details about the apparatus from the SI should be included (esp. for HPLC, HRMS, NMR) in the `details` fields of those analyses.

**Comment by skearnes** [comment]
Hi @wert0069, just checking on this PR. Did you have any questions about the review comments?

**Comment by skearnes** [comment]
Hi @wert0069, should we close this PR?

**Comment by wert0069** [comment]
Hi sorry for the late reply, yes go ahead and close the PR. Thanks!

**Comment by skearnes** [comment]
Sounds good; please feel free to reopen in the future.

**Pull request closed without merging**
