### PR TITLE
Add USPTO grants

### PR DESCRIPTION
**Pull request by skearnes**
Parsed from CML and sharded by year:

```bash
for year in ~/uspto/grants/*; do
  YEAR="$(basename "${year}")"
  python ord_schema/scripts/parse_uspto.py \
    --input_pattern="${HOME}/uspto/grants/${YEAR}/*.xml" \
    --name="uspto-grants-${YEAR}" \
    --output="../ord-data/grants-${YEAR}.pb" \
    --n_jobs=-1
done
```

### CODE REVIEW

**Comment by skearnes** [comment]
Arg; actions is OOM-ing. Might have to submit in smaller chunks.

**Comment by skearnes** [comment]
FYI I decided to go with gzip compression after all---it reduces the size/time of the clone by 80% and conserves our Git LFS bandwidth quota (also 50 GB/mo.)

**Comment by skearnes** [comment]
Currently blocked by https://github.com/open-reaction-database/ord-schema/pull/551 and https://github.com/open-reaction-database/ord-schema/pull/552.

**Comment by skearnes** [comment]
(I changed the target branch, but I'm not going to re-run the tests since it took almost 6 hours.)

**Review by connorcoley — APPROVED** [review]

**Pull request merged**
