### PR TITLE
Miniaturised Suzuki couplings, reductive aminations, and N-alkylation

### PR DESCRIPTION
**Pull request by bdeadman**
…s (#202)

* 1440 suzuki rxns

1440 suzuki rxns from https://doi.org/10.1038/s44160-023-00351-1.

* added first subset of reductive aminations, and added name for suzuki dataset

* now with all 3 dataset files including updates to suzuki and red am

* Rogue quotation mark in description - fixed

* Delete alkylation_merge.pbtxt

* Fixed tag on core_SMILES outcome

* Added dataset name and descriptor to Suzuki

### CODE REVIEW

**Comment by bdeadman** [comment]
1440 Suzuki rxns, 768 reductive aminations, and 104 N-alkylations with BOC deprotection. From [https://doi.org/10.1038/s44160-023-00351-1](https://doi.org/10.1038/s44160-023-00351-1), a paper by Tim Cernak when he was at Merck. Reactions are miniaturized to uL scale.

[submission.zip](https://github.com/user-attachments/files/17246741/submission.zip) has the templates and the csv files. Note that the N-alkylation set was assembled in two parts and then joined together to correctly format the control reactions.

**Comment by bdeadman** [comment]
@skearnes - these three haven't been peer reviewed yet.

**Comment by skearnes** [comment]
Thanks @bdeadman! Review notes:

### Suzuki

* Check names in the dataset description.
* There's no addition order 2? I see two inputs with addition order 4 in the template.
* H2O is listed as 1600 nmol; should that be nL?
* Should you include the boronate reactant in the product list if it has no associated measurements?
* You include the row in the analytical data but I think this is already in the reaction identifiers?

### Amination

* Does this dataset only include the optimization set and not the library set? I see two sheets in the SI with 768 and 384 rows.
* I'm confused about the solvent placeholders; from the SI it looks like NMP was used a lot but I'm not seeing it?

### Alkylation

* I see some unpopulated values, like `$Electrophile ID$` in the final reaction.
* The `base` input has no SMILES.
* Typo in "Forumula" in product identifiers.

**Comment by bdeadman** [comment]
Suzuki

- Boronic acid/ester is addition 2, and catalyst is addition 3.
- The H2O is included in the core stock solution at 4 equivalents level, but the value should be 400 (not 1,600).
- Removed the boronate from the products. This was possibly my 'working' in the GUI to check SMILES but I must have missed deleting it.
- Deleted well row from analytical details. This was a late change to make it consistent with the other datasets in this paper.
- Corrected Time to Tim in dataset description.

Dataset .pb.gz file has been replaced and pushed to this branch.
Files to generate dataset: [Cernak_miniature_suzuki_v2.zip](https://github.com/user-attachments/files/17309423/Cernak_miniature_suzuki_v2.zip)

**Comment by bdeadman** [comment]
### Reductive Amination
- Current dataset only includes the optimisation. I will add the library set to the same dataset.
- Not sure what the problem is here. In the optimisation set half the reactions are run in DMA, and the other half in NMP. The dataset on my PC looks to have the solvents setup. When I add the extra library data we can check again.

**Comment by bdeadman** [comment]
### Alkylation Dataset

- $Electrophile ID$ had a double space in the spreadsheet. Changed key and column header to Electrophile_ID for clarity.
- Base SMILES had a few empty cells in the source spreadsheet. Resolved.
- "Forumula" typo corrected.
- Changed the deprotected core product to have is_desired_product = false

Replacement source files: [alkylation.zip](https://github.com/user-attachments/files/17328651/alkylation.zip)

**Comment by bdeadman** [comment]
@skearnes I've made the updates and replaced the .pb.gz files. the reaction count looks correct. Let me know if there are any other changes required.

**Comment by skearnes** [comment]
Thanks @bdeadman. A few minor comments:

### Alkylation

- [ ] The "Electrophile ID" compound identifier should have a `CUSTOM` type, not `UNSPECIFIED`.

### Amination

- [ ] The "Building Block" compound identifier should have a `CUSTOM` type, not `UNSPECIFIED`.

### Suzuki

- [ ] The "Monomer ID" compound identifier should have a `CUSTOM` type, not `UNSPECIFIED`.

**Review by skearnes — APPROVED** [review]

**Comment by skearnes** [comment]
> Thanks @bdeadman. A few minor comments:
> 
> ### Alkylation
> * [ ]  The "Electrophile ID" compound identifier should have a `CUSTOM` type, not `UNSPECIFIED`.
> 
> ### Amination
> * [ ]  The "Building Block" compound identifier should have a `CUSTOM` type, not `UNSPECIFIED`.
> 
> ### Suzuki
> * [ ]  The "Monomer ID" compound identifier should have a `CUSTOM` type, not `UNSPECIFIED`.

Actually this might be a schema version issue; I see the actual data has the "MDL" type for "Electrophile ID". I'll investigate.

**Comment by skearnes** [comment]
Yes, that was it; waiting on https://github.com/open-reaction-database/ord-interface/pull/138. This PR is good to go.

**Pull request merged**
