### PR TITLE
Adds Nielsen deoxyfluorination dataset

### PR DESCRIPTION
**Pull request by michaelmaser**
Dataset created from [notebook](https://github.com/open-reaction-database/ord-schema/blob/6494172eeebcfd57f68f723c54fef20ef0a4ccbd/examples/submissions/2_Nielsen_Deoxyfluorination_Screen/example_nielsen.ipynb) in ord-schema by @connorcoley.

### CODE REVIEW

**Comment by skearnes** [comment]
Thanks @michaelmaser! A few comments:

* [ ] The SI says "8 x 40 mm" glass vial; should this be included somewhere? I assume the 1 mL annotation is inferred from that size?
* [ ] Add `volume_includes_solutes = False` to the solvents (including in the workup)?
* [ ] The chloroform added in the workup should be deuterated (also update the corresponding description).
* [ ] The non-synthesized SFs (PyFluor and PBSF) should be indicated in `build_compound`.
* [ ] The vendor for PyFluor should be specified.
* [ ] Please add the names of the SFs so the records are easier to read.
* [ ] The logic to build out the table doesn't seem to correctly copy preparations (I expected to see SYNTHESIZED for the randomly chosen reaction shown in the notebook).

**Comment by michaelmaser** [comment]
Thanks, @skearnes! Think I got everything. Added a `record_modified` for posterity.

**Comment by skearnes** [comment]
> Thanks, @skearnes! Think I got everything. Added a `record_modified` for posterity.

Thanks! Would you mind attaching the updated notebook---or linking to a PR on ord-schema with the changes?

**Comment by michaelmaser** [comment]
> Thanks! Would you mind attaching the updated notebook---or linking to a PR on ord-schema with the changes?

Sure thing, attached here. Happy to create a PR, maybe next office hours.
[example_nielsen.ipynb.zip](https://github.com/open-reaction-database/ord-data/files/6863466/example_nielsen.ipynb.zip)

**Comment by skearnes** [comment]
Thanks! One more question: where is the stereochemistry information coming from for e.g. 1a in the example reaction? I don't see that in the SI or paper anywhere?

**Review by skearnes — APPROVED** [review]

**Comment by skearnes** [comment]
> Thanks! One more question: where is the stereochemistry information coming from for e.g. 1a in the example reaction? I don't see that in the SI or paper anywhere?

Nevermind; was looking at the wrong structure.

**Comment by michaelmaser** [comment]
Thanks! Any idea why the check_file_types is failing?

**Comment by skearnes** [comment]
I think it's because the target branch is out of date, and the job does a comparison vs. `main`. If you update `nielsen` it should work, but I wouldn't worry about it.

**Comment by michaelmaser** [comment]
Worked, thanks!

**Pull request merged**
