### PR TITLE
Dataset 47463309 1

### PR DESCRIPTION
**Pull request by qai222**
resubmit https://github.com/open-reaction-database/ord-data/pull/183
based on discussion in https://github.com/open-reaction-database/ord-data/issues/193

 changes:
- pre-mix are now in `ReactionConditions`
- two `ProductCompound` are used to represent the enantiomers, each with a unique chiral SMILES
- signs of ee values were corrected 
- peak area were calculated for individual enantiomers based on the total reported peak area and ee

note:
- derivatization reaction: I still included the steps for derivatization reaction as `ReactionWorkup` instances as I feel they are still important, especially when solvent/catalyst/conditions of the derivatization are all different from the main reaction.

### CODE REVIEW

**Comment by bdeadman** [comment]
Thanks @qai222. I'll review it tonight. I was about to say add the description I can see you found the validation error.

**Comment by qai222** [comment]
Could you @bdeadman  please wait a bit before reviewing this submission? I may need to modify it again as I have not included derivatization products as `ProductCompound`. I'm thinking how to link the derivative product to the intended desired product.

**Comment by qai222** [comment]
@bdeadman the submission is ready for review

**Comment by bdeadman** [comment]
micro symbols in string text entries showing as \316\274 => suggest changing this to "u", and have already made this change to process.py in [my fork of your submission repo](https://github.com/bdeadman/qai_ord_submission/tree/master/dataset_47463309) 

The first two workup steps (take 4 uL and dilute with 36 uL ACN) appear to be duplicated.

workups {
    type: ALIQUOT
    details: "4 \316\274L mixture of each reacted solution was collected and diluted with 36 \316\274L ACN"
    amount {
      volume {
        value: 4.0
        units: MICROLITER
      }
    }
  }
  workups {
    type: ADDITION
    details: "4 \316\274L mixture of each reacted solution was collected and diluted with 36 \316\274L ACN"
    input {
      components {
        identifiers {
          type: SMILES
          value: "CC#N"
        }
        amount {
          volume {
            value: 36.0
            units: MICROLITER
          }
        }
        reaction_role: WORKUP
      }
      addition_device {
        type: PIPETTE
        details: "VERSA 110, Aurora Biomed, Canada"
      }
    }
  }

Some of the EE selectivity values are -- instead of +, e.g. 

products {
      identifiers {
        type: SMILES
        value: "C#CCCC[C@@H](C=O)CC(=O)c1ccccc1"
      }
      identifiers {
        type: CUSTOM
        details: "enantiomer label"
        value: "S config"
      }
      is_desired_product: true
      measurements {
        analysis_key: "IM-MS"
        type: SELECTIVITY
        uses_internal_standard: true
        percentage {
          value: 59.44
        }
        selectivity {
          type: EE
          details: "--59.44%"

**Comment by bdeadman** [comment]
Changed target to branch so that the automated submission workflows will be run after the merge.

**Comment by qai222** [comment]
> For a quick fix of those 3 issues I could do use a text editor to do find/replace on the .pbtxt dataset.
> 
> @qai222 let me know if you want me to take care of this.

That would be great as I don't have ord environment on my current workstation. Thanks!

**Pull request merged**
