### PR TITLE
Uploading Dataset for https://doi.org/10.1039/C5SC04751J Partial Figure 4

### PR DESCRIPTION
**Pull request by mwleklin**
This dataset was prepared using the online enumerator. This is reactions related to entries 11-15 in figure 4 of the paper. 

[Submission.zip](https://github.com/open-reaction-database/ord-data/files/6591584/Submission.zip)

### CODE REVIEW

**Comment by skearnes** [comment]
I'm seeing an error in the automated validations:

```
W0603 12:25:00.525358 139843574585152 validations.py:126] Validation error for Figure4_dataset.pbtxt: Dataset: Multiple Reactions should never have the same IDs
Traceback (most recent call last):
  File "./ord-schema/ord_schema/scripts/process_dataset.py", line 320, in <module>
    app.run(main)
  File "/usr/share/miniconda/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/share/miniconda/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "./ord-schema/ord_schema/scripts/process_dataset.py", line 316, in main
    run()
  File "./ord-schema/ord_schema/scripts/process_dataset.py", line 271, in run
    validations.validate_datasets(datasets, FLAGS.write_errors)
  File "/usr/share/miniconda/lib/python3.7/site-packages/ord_schema-0.0.0-py3.7.egg/ord_schema/validations.py", line 86, in validate_datasets
    raise ValidationError(f'validation encountered errors:\n{error_string}')
ord_schema.validations.ValidationError: validation encountered errors:
Figure4_dataset.pbtxt: Dataset: Multiple Reactions should never have the same IDs
```

It looks like this might be caused by having a reaction ID defined in the template before enumeration? If so, would you mind clearing the ID and then re-enumerating?

**Comment by skearnes** [comment]
(Or you could just delete the reaction IDs from the current pbtxt.)

**Comment by mwleklin** [comment]
Okay redid the enumeration and removed the reaction ID. It looks like that reaction came along when I downloaded the file I used to do template the enumeration.

**Comment by skearnes** [comment]
Validations are passing now, thanks!

**Comment by brilee** [comment]
@skearnes I'm seeing a blank screen on the editor when I download this .pbtxt from the pull request and upload it to https://editor.open-reaction-database.org/ 

Not quite sure what I'm doing wrong here - any ideas?

**Comment by skearnes** [comment]
> @skearnes I'm seeing a blank screen on the editor when I download this .pbtxt from the pull request and upload it to https://editor.open-reaction-database.org/
> 
> Not quite sure what I'm doing wrong here - any ideas?

I'm seeing the same thing. If I load the dataset in python and then rewrite it as a `*.pb` it seems to work. No idea why, but I can do some digging.

**Comment by brilee** [comment]
for posterity, the command I used to convert the pbtxt:

```
from ord_schema.proto import dataset_pb2
from ord_schema import message_helpers
msg = message_helpers.load_message('Figure4_dataset.pbtxt', dataset_pb2.Dataset)
message_helpers.write_message(msg, 'Figure4_dataset.pb')
```

**Comment by brilee** [comment]
I reviewed reaction #0 for all the procedures. All good except I think the internal standard calculation is incorrect.

The SI says "For the internal standard:  diluted with 100 μL of 5% AcOH in DMSO, containing 1,3,5-trimethoxybenzene (0.005M)"

which is 1e2 * 1e-6 L* 5e-3 mol/L = 5e-7 mol, or 0.5 micromole. I'm seeing 0.05 micromoles listed on reaction #0.

I also manually checked the structures on reactions 0~17 (for the aryl halides) and the catalyst structures on reaction 0, 18, 36, 54, and 72. Everything looks good.

**Review by brilee — APPROVED** [review]

**Comment by skearnes** [comment]
@mwleklin any updates re: Brian's comments above?

**Comment by mwleklin** [comment]
Just noticed these comments. Checked the math as well and agree it should be 0.5 micromole. This a case where I should change it and reupload it?

**Comment by skearnes** [comment]
> Just noticed these comments. Checked the math as well and agree it should be 0.5 micromole. This a case where I should change it and reupload it?

Yes, please.

**Comment by mwleklin** [comment]
> > Just noticed these comments. Checked the math as well and agree it should be 0.5 micromole. This a case where I should change it and reupload it?
> 
> Yes, please.

All done. Any concern about the check file type error?

**Comment by skearnes** [comment]
> All done. Any concern about the check file type error?

Thanks. Looks like the target branch was out of date; updated.

**Comment by skearnes** [comment]
@brilee PTAL?

**Review by brilee — APPROVED** [review]
apologies for the delay. LGTM.

**Pull request merged**
