### PR TITLE
Uploading dataset pbtxt for Shields Doyle Paper

### PR DESCRIPTION
**Pull request by Jesus00-1**
Pbtxt files were created using the interactive web editor. Reactions are from the paper https://doi.org/10.1038/s41586-021-03213-y. 
Template reactions pbtxt and csv files are attached.

Note 0% Yields did not show up in the schema when checking for consistency.

This is an enumerated dataset of 1728 reactions from imidazole arylation for figure S42.

[Shields_arylation_figS42.zip](https://github.com/open-reaction-database/ord-data/files/5927349/Shields_arylation_figS42.zip)

This is an enumerated dataset of 256 reactions from imidazole arylation for figure S45 (Extended ligand set for testing model out of sample prediction performance)

[experiment_index_extended_dataset.zip](https://github.com/open-reaction-database/ord-data/files/5927409/experiment_index_extended_dataset.zip)

### CODE REVIEW

**Comment by Jesus00-1** [comment]
The extended ligand set was not labeled. It is attached with a label here.

[experiment_index_extended_dataset_labeled.zip](https://github.com/open-reaction-database/ord-data/files/5927636/experiment_index_extended_dataset_labeled.zip)

**Comment by skearnes** [comment]
Hi @Jesus00-1, thanks for the PR and the bug report. I've updated the web editor with #81; would you mind re-adding the zero yield values to the submission? They should be preserved now.

**Comment by Jesus00-1** [comment]
Hi, 

They are attached. Let me know if there is anything else I need to do on my end.

Figure S42 and the extended dataset (S45)

[experiment_index_S42.zip](https://github.com/open-reaction-database/ord-data/files/5937684/experiment_index_S42.zip)

[experiment_index_extended.zip](https://github.com/open-reaction-database/ord-data/files/5937685/experiment_index_extended.zip)

Thank you!

**Comment by skearnes** [comment]
Oh, sorry, would you mind *committing* the updated files so they can be merged in this PR?

**Comment by skearnes** [comment]
> Oh, sorry, would you mind _committing_ the updated files so they can be merged in this PR?

(If it's easier, feel free to a create a new PR with the updated pbtxt.)

**Pull request closed without merging**
