### PR TITLE
Expt2 10.1021/acs.accounts.0c00760

### PR DESCRIPTION
**Pull request by mwleklin**
1728 Reactions (all of them) from Figure 6 of 10.1021/acs.accounts.0c00760
This was generated using the interactive web tool and associated enumerator. 
Type of chemistry is C-N photoredox. 
18 Aryl Halides
12 Catalysts
2 Monomer Loading
4 Catalysts Loading
18x12x2x4 = 1728

[Submission.zip](https://github.com/open-reaction-database/ord-data/files/6666039/Submission.zip)

### CODE REVIEW

**Comment by connorcoley** [comment]
Sorry for the delay @mwleklin  -- is the experimental procedure for this dataset published? I can't seem to find a detailed description that matches the template reaction. The SI for the Accounts paper looks different in terms of scope.

**Comment by mwleklin** [comment]
Sorry for my delay @connorcoley . This replicate the image from S12, which has the 4 Ni:Ir loadings and two amine loadings. 

In terms of the number of informers, the paper appears to be wrong in the supporting information wording. Figure 6 in the main text and figure S12 both show 18 informers. Additionally, Spencer and I built these together so the number should be correct. 

Apologies for not being more descriptive early on with the data source, will include in the future.

**Comment by connorcoley** [comment]
Got it, thanks! Before I approve, do you mind addressing the one quick dataset-level comment? It's helpful to note what figure/subset of the paper the data should correspond to

> Can you be sure to give the dataset a name and description (post-enumeration)?

**Comment by mwleklin** [comment]
Done, Let me know if the name and description should be formatted differently. 

-Mike

**Review by connorcoley — APPROVED** [review]
Nope, that looks great! Thanks

**Pull request merged**
