### PR TITLE
Huffman islatravir dataset submission (#91)

### PR DESCRIPTION
**Pull request by michaelmaser**

### CODE REVIEW

**Comment by brilee** [comment]
is there something new in this dataset or do you just need a rubber-stamp to check it into the git-LFS system?

**Comment by brilee** [comment]
ooh, I see - the [PR I previously reviewed ](https://github.com/open-reaction-database/ord-data/pull/91)was just merely merged into this branch

**Review by brilee — APPROVED** [review]

**Comment by michaelmaser** [comment]
Yes, thanks! Is there a way to trigger the `process_submission` check that I'm missing?

**Comment by connorcoley** [comment]
Usually closing and re-opening is enough. @skearnes ?

**Comment by skearnes** [comment]
Hmm...that key error suggests we aren't doing the linking between reactions correctly; I'll take a look tomorrow.

**Comment by skearnes** [comment]
@michaelmaser should be good to go. Please double-check the cross-references before merging.

**Review by skearnes — APPROVED** [review]

**Comment by michaelmaser** [comment]
Thanks, @skearnes! Cross-references looked good in loaded pb.

**Pull request merged**
