### PR TITLE
Updating dataset with Suzuki informer library

### PR DESCRIPTION
**Pull request by jun-li-2020**
[Pd_CN_Coupling_template_spreadsheet.zip](https://github.com/Open-Reaction-Database/ord-data/files/5253155/Pd_CN_Coupling_template_spreadsheet.zip)
[Suzuki _template_spreadsheet.zip](https://github.com/Open-Reaction-Database/ord-data/files/5253139/Suzuki._template_spreadsheet.zip)

Uploaded the Suzuki template and 120-rxn spreadsheet csv file.
Kutchukian et al "Chemistry informer libraries: a chemoinformatics enabled approach to evaluate and advance synthetic methods"
Ref: Chem. Sci., 2016, 7, 2604
doi: 10.1039/c5sc04751j

### CODE REVIEW

**Comment by connorcoley** [comment]
Thanks @jun-li-2020 ! Would it be possible for you to share the templates and spreadsheets you used for the enumeration here? You might have to .zip the files for GitHub to let you upload them

**Comment by jun-li-2020** [comment]
> Thanks @jun-li-2020 ! Would it be possible for you to share the templates and spreadsheets you used for the enumeration here? You might have to .zip the files for GitHub to let you upload them

I have just attached zip file incl the Suzuki template and 120-rxn spreadsheet.

**Comment by connorcoley** [comment]
We're still refining the review process, so feel free to let me know if the structure of this feedback makes sense:

**_Overall comments_**
1. It would be good to add dataset-level comments specifying where these reactions appear in the paper. For example, the CN data is the first 8 rows of Figure 4D. The Suzuki data is the first 5 rows of Figure 3D.

***C-N Coupling***
1. The inputs in the template look terrific to me for the first 8 entries/rows of Figure 4D.
1. There is quite a bit of information about the setup in the General Information section of the SI as to the source/part of the 250 microliter microvials and stir bars. There's also information about how the reaction plates are sealed. These aren't essential details to add, but I want to point out that there are fields to accommodate them.
1. One of the key pieces of information we'd like to capture is *how* yields/etc. were calculated. For this dataset, it seems important to record (a) the addition of 100 μL of 5% AcOH in DMSO containing 1,3,5-trimethoxybenzene (0.005M); (b) aliquoting 25 microliters from the vial; (c) diluting with 700 microliters of aceonitrile before quantitative UPLC analysis. These would be considered workup steps.
1. On a related note, knowing that the yields were determined by UPLC using an internal standard and a calibration curve produced using an authentic standard is significant; it's good to know these are "real" yields, or at least more accurate than relative UV peak areas.
1. For templating, how did you deal with the fact that Figure 4D, Entry 2 contains two components for the catalyst/ligand (i.e., the J-009 and Pd(OAc)2)? Did you just record the complex it forms?

***Suzuki***
1. I haven't checked all of the substrates in detail yet, but I think my comments would be similar to the CN comments. Specifying the workup steps, analysis method, and means of yield_analysis would make this a very strong contribution.

**Comment by jun-li-2020** [comment]
> We're still refining the review process, so feel free to let me know if the structure of this feedback makes sense:
> 
> Thanks for sharing the inputs to the enumeration step -- these are what I reviewed for the comments below:
> 
> **_Overall comments_**
> 
> 1. It would be good to add dataset-level comments specifying where these reactions appear in the paper. For example, the CN data is the first 8 rows of Figure 4D. The Suzuki data is the first 5 rows of Figure 3D.
> 
> _**C-N Coupling**_
> 
> 1. The inputs in the template look terrific to me for the first 8 entries/rows of Figure 4D.
> 2. There is quite a bit of information about the setup in the General Information section of the SI as to the source/part of the 250 microliter microvials and stir bars. There's also information about how the reaction plates are sealed. These aren't essential details to add, but I want to point out that there are fields to accommodate them.
> 3. One of the key pieces of information we'd like to capture is _how_ yields/etc. were calculated. For this dataset, it seems important to record (a) the addition of 100 μL of 5% AcOH in DMSO containing 1,3,5-trimethoxybenzene (0.005M); (b) aliquoting 25 microliters from the vial; (c) diluting with 700 microliters of aceonitrile before quantitative UPLC analysis. These would be considered workup steps.
> 4. On a related note, knowing that the yields were determined by UPLC using an internal standard and a calibration curve produced using an authentic standard is significant; it's good to know these are "real" yields, or at least more accurate than relative UV peak areas.
> 5. For templating, how did you deal with the fact that Figure 4D, Entry 2 contains two components for the catalyst/ligand (i.e., the J-009 and Pd(OAc)2)? Did you just record the complex it forms?
> 
> _**Suzuki**_
> 
> 1. I haven't checked all of the substrates in detail yet, but I think my comments would be similar to the CN comments. Specifying the workup steps, analysis method, and means of yield_analysis would make this a very strong contribution.

Thank you Connor for your detailed review!  I absolutely agree with you that details in workup/analysis are critical to capture for interpreting the quality of the high throughput screening results. I have updated the templates for both Suzuki and C-N cross coupling by adding the workup (quench info with internal standard) and aliquoting info in the analysis section along with the analytical methods. Pls note that the internal standard was introduced differently in the Suzuki dataset. It was added along with bornoate ester from the beginning rather than during the workup.   As for the ligand/Pd(OAc)2 info from entry#2 in the C-N coupling dataset, since the moles of the ligand component in the whole screening set are kept the same, for the sake of the simplicity, I deliberately chose the ligand only SMILES info in the catalyst section as long as we use moles as the measuring unit, and added the info of moles of Pd(OAc)2 used in the preparation detail section manually after enumeration for all the 18 examples in the entry #2 to capture the molar ratio relationship.  I did not attempt to draw the precatalyst complex between J-009 and Pd.  I felt that the inaccurate drawing on the fictitious complex could do more harm later.  Also, in the future for machine learning purposes, the extraction of the ligand only SMILES from precatalyst complex might be more informative when comparing across the ligand libraries.  Here attached are the updated templates along with the newly enumerated datasets in the zip file. 

[Pd_CN_Coupling_template_spreadsheet_09222020.zip](https://github.com/Open-Reaction-Database/ord-data/files/5262269/Pd_CN_Coupling_template_spreadsheet_09222020.zip)
[Suzuki_template_spreadsheet_09222020.zip](https://github.com/Open-Reaction-Database/ord-data/files/5262273/Suzuki_template_spreadsheet_09222020.zip)

**Comment by connorcoley** [comment]
This is terrific! I've made minor modifications to the templates (attached) if you don't mind using those. The only changes are the following:
- Adding the 5 min vigorous stirring step to the Suzuki workup
- Adding the UPLC and UPLC-MS analysis keys to the "analysis_yields" fields of the product so that it's explicitly stated that the yields were calculated using these analyses.
- I've removed "preparations" for components that describe the overall input or stock solution. For example, the details for the DMSO component of the workup in the CN case described the whole solution that was added. We're intending compound preparations to be specific to individual components; the fact that 100 uL of 5% acetic acid in DMSO with 0.005M 1,3,5-trimethoxybenzene was prepared is captured by the components+amounts already.
- I've removed the NAME identifiers from the Suzuki input containing the combined boronate and internal standard and a few other components. The roles should be captured by the reaction_role assignment already; the name identifiers are more meant to be the common names of the compounds, not shorthand descriptions.

Let me know if these changes make sense to you.  Your method of handling the additional component in the CN entry number two (manual addition after enumeration) sounds like a good short-term solution. Steve and I are working on a way to make that easier in the future, but I'm glad it wasn't too tedious for this dataset. 

Representing and storing catalyst complexes is a very tricky business, as you know. I agree that extracting the ligand-only SMILES might end up being most useful for machine learning.

[Archive.zip](https://github.com/Open-Reaction-Database/ord-data/files/5279343/Archive.zip)

@skearnes , anything to add?

**Comment by jun-li-2020** [comment]
> This is terrific! I've made minor modifications to the templates (attached) if you don't mind using those. The only changes are the following:
> 
> * Adding the 5 min vigorous stirring step to the Suzuki workup
> * Adding the UPLC and UPLC-MS analysis keys to the "analysis_yields" fields of the product so that it's explicitly stated that the yields were calculated using these analyses.
> * I've removed "preparations" for components that describe the overall input or stock solution. For example, the details for the DMSO component of the workup in the CN case described the whole solution that was added. We're intending compound preparations to be specific to individual components; the fact that 100 uL of 5% acetic acid in DMSO with 0.005M 1,3,5-trimethoxybenzene was prepared is captured by the components+amounts already.
> * I've removed the NAME identifiers from the Suzuki input containing the combined boronate and internal standard and a few other components. The roles should be captured by the reaction_role assignment already; the name identifiers are more meant to be the common names of the compounds, not shorthand descriptions.
> 
> Let me know if these changes make sense to you. Your method of handling the additional component in the CN entry number two (manual addition after enumeration) sounds like a good short-term solution. Steve and I are working on a way to make that easier in the future, but I'm glad it wasn't too tedious for this dataset.
> 
> Representing and storing catalyst complexes is a very tricky business, as you know. I agree that extracting the ligand-only SMILES might end up being most useful for machine learning.
> 
> [Archive.zip](https://github.com/Open-Reaction-Database/ord-data/files/5279343/Archive.zip)
> 
> @skearnes , anything to add?
Thank you for your modifications!  They all make sense.  One minor comment on the "5% acetic acid in DMSO", sometimes, the reader may be unsure about whether this is weight or volume percentage referred in the preparation of the stock solution.  My hunch was v/v based on typical practices in an analytical lab. However, if the procedure was related to scale-up processes, the operator is more likely using weight based approach to record material inputs and ratios for preparation of solutions.

**Comment by skearnes** [comment]
Thanks @jun-li-2020; this is great! And thanks @connorcoley for digging in and providing suggestions on the template.

Could you please push a new commit with the newly enumerated dataset using the updated template?

**Comment by jun-li-2020** [comment]
> Thanks @jun-li-2020; this is great! And thanks @connorcoley for digging in and providing suggestions on the template.
> 
> Could you please push a new commit with the newly enumerated dataset using the updated template?

Thank you Steve, I just pushed a new commit with the finalized datasets I have updated using Connor's suggested templates with a very minor modification in Suzuki template. In Suzuki dataset, I noticed that the added "5-min stirring" under the workup section has no corresponding component, the input component was used in the prior addition step in the original workup section. To resolve the issue, I replaced the "addition" with "stirring".  everything looks ok now.

**Comment by skearnes** [comment]
@jun-li-2020 you found a bug in our automated processing script! Hold on while I create a PR to fix it...

**Comment by skearnes** [comment]
One last thing @jun-li-2020: Can you please upload a zip with the latest template and spreadsheet? It's nice to have a record of these on the PR.

**Comment by skearnes** [comment]
Oops, I meant could you please add them to the PR as a comment attachment? We don't want to include the zipfiles in the commits...

**Review by skearnes — APPROVED** [review]
Thanks @jun-li-2020

**Pull request merged**
