### PR TITLE
Pfizer HTE Suzuki dataset from @wshlau

### PR DESCRIPTION
**Pull request by skearnes**
Copy of https://github.com/open-reaction-database/ord-data/pull/137 from @wshlau

### CODE REVIEW

**Review by ipendlet — APPROVED** [review]

**Review by ipendlet — COMMENTED** [review]
Pending chemistry review

**Comment by ipendlet** [comment]
Hi @wshlau. Can you tell us a bit more about the experiments that you are trying to commit here? These don't look like the original work from the cited paper. Are these reactions reproductions that you did in lab? Are they associated independently with any ongoing publication?

We like the idea of including both, but it is important to maintain a clear audit log of where reactions are coming from and what they were intended to capture (i.e., reproducibility, replicability, new chemistry, etc).

**Review by ipendlet — CHANGES_REQUESTED** [review]
Update to correct metadata

**Review by ipendlet — APPROVED** [review]

**Comment by skearnes** [comment]
> Update to correct metadata

Was this done? I don't see any new commits.

**Comment by ipendlet** [comment]
@skearnes this is now ready for merge if you don't have additional changes.

**Pull request merged**
