### PR TITLE
Huffman islatravir biocatalytic cascade dataset submission

### PR DESCRIPTION
**Pull request by michaelmaser**
Details the synthesis of islatravir by enzymatic catalysis. 

Notebook used for generation is attached, which includes links to the paper and images of each reaction scheme from the SI for visualization.

[Huffman_islatravir_dataset.ipynb.zip](https://github.com/open-reaction-database/ord-data/files/6555468/Huffman_islatravir_dataset.ipynb.zip)

### CODE REVIEW

**Comment by brilee** [comment]
- in rxn1 sulfur pentahydrate is drawn as the hexahydrate
- in rxn2, water solvent is doubly specified?
- rxn3 - holy crap that cascade is magic

I notice there's a lot of solutions in this one. Do you want to review and give the macros in https://github.com/open-reaction-database/ord-schema/pull/599 a whirl?

The 1H NMR, 13C NMR, 31P NMR, HRMS data is nice.

**Review by brilee — APPROVED** [review]

**Comment by michaelmaser** [comment]
Thanks for the feedback, Brian!

> * in rxn1 sulfur pentahydrate is drawn as the hexahydrate

Are you sure? Just loaded the SMILES from the pbtxt into RDKit and see the pentahydrate below:
cuso4_5h2o

> * in rxn2, water solvent is doubly specified?

Yes, the substrate is a solution in water, but the `crude_component` can't be specified as a solution if you want to include the mass of the compound (since they know the exact amount of the substrate, I wanted to use it). So, I added the crude substrate as it's mass, with an input of the proper volume of water at the same addition order. Then, one of the reagents is also added as an aqueous solution, which was treated normally as a single input.

> I notice there's a lot of solutions in this one. Do you want to review and give the macros in [open-reaction-database/ord-schema#599](https://github.com/open-reaction-database/ord-schema/pull/599) a whirl?

Cool, thanks! For the sake of time, I'm hoping to submit ASAP since this dataset will be referenced in the manuscript. Would be happy to try it out after/with the next dataset!

> The 1H NMR, 13C NMR, 31P NMR, HRMS data is nice.

Thanks!

**Comment by brilee** [comment]
Ah, double-checked the pentahydrate and it's correct - my bad. Everything else seems good to me

**Comment by michaelmaser** [comment]
No worries, thanks again! @skearnes @connorcoley any concerns before I submit?

**Comment by connorcoley** [comment]
Just changing the PR so you're merging into a branch and not main, but I'll trust Brian's review and the process!

**Comment by skearnes** [comment]
Thanks @michaelmaser  --- can you please create the second PR to merge that branch into main now?

**Pull request merged**
