### PR TITLE
Dataset from 24Golden paper Fig 7 #194

### PR DESCRIPTION
**Pull request by bdeadman**
#194

### CODE REVIEW

**Comment by bdeadman** [comment]
@skearnes @connorcoley

I've already reviewed this data from the Stahl group so it should just need a review to confirm it can move from the branch to main.

**Comment by connorcoley** [comment]
Is this meant to just be a single reaction?

**Comment by bdeadman** [comment]
It should be 288 reactions. I've downloaded the file from the open-reaction-database:#194 branch to check it again (see below).

image

**Comment by bdeadman** [comment]
The count_reactions workflow was failing and giving the following error:

INFO 2024-08-05 13:06:56,894 reactions.py:40: data/c2/ord_dataset-c2ad1656a3ca4d08888ffb6e3f3a2742.pb.gz:	2701
HEAD detached at 9aa515c
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	ord-schema/

nothing added to commit but untracked files present (use "git add" to track)
warning: redirecting to https://github.com/open-reaction-database/ord-data.git/
Uploading LFS objects: 100% (526/526), 1.2 GB | 0 B/s, done.
To https://github.com/open-reaction-database/ord-data.git
 ! [rejected]        HEAD -> #194 (fetch first)
error: failed to push some refs to 'https://github.com/open-reaction-database/ord-data.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Process completed with exit code 1.


To solve I have removed the new dataset on my local open-reaction-database:#194 repo, committed and pushed the change, then added the file (the post ORD processing version) back in, commit and push again. Now the workflows run again and count_reactions shows the correct 288 added.

**Comment by bdeadman** [comment]
@connorcoley @skearnes  The problem with the reaction count has been resolved. How it happened may be worth a discussion at some point, but I'll see if it happens again.

This dataset should be ready for release.

**Review by skearnes — APPROVED** [review]

**Pull request merged**
