### PR TITLE
Add Baumgartner et al. C-N reaction dataset

### PR DESCRIPTION
**Pull request by marcosfelt**
Add data from this paper: http://doi.org/10.1021/acs.oprd.9b00236

Code used to generate dataset is here: https://github.com/sustainable-processes/multitask/blob/69606a102b981bf2c207efd72741503fc4a349e3/multitask/etl/etl_baumgartner_cn.py

### CODE REVIEW

**Comment by marcosfelt** [comment]
Also, could you add Daniel Wigh <dswigh@gmail.com> as a contributor on this PR in the final commit message?

**Comment by skearnes** [comment]
> Also, could you add Daniel Wigh [dswigh@gmail.com](mailto:dswigh@gmail.com) as a contributor on this PR in the final commit message?

Does Daniel have a GitHub account? We can tag him here as a contributor but unless he makes a commit he won't be in the git history. Alternatively, you could add him in the provenance section of the reactions?

**Comment by skearnes** [comment]
These reactions seem to be missing provenance---maybe you need to add a new commit after updating the code?

**Comment by skearnes** [comment]
Can you please add these notes (https://github.com/sustainable-processes/multitask/blob/69606a102b981bf2c207efd72741503fc4a349e3/multitask/etl/etl_baumgartner_cn.py#L6) and a link to the code in the dataset description?

**Comment by skearnes** [comment]
Can you please add the conversion values here: https://github.com/open-reaction-database/ord-schema/blob/main/proto/reaction.proto#L844

**Comment by skearnes** [comment]
> Can you please add these notes (https://github.com/sustainable-processes/multitask/blob/69606a102b981bf2c207efd72741503fc4a349e3/multitask/etl/etl_baumgartner_cn.py#L6) and a link to the code in the dataset description (not just the PR description)?

Link to the relevant field: https://github.com/open-reaction-database/ord-schema/blob/main/proto/dataset.proto#L27

**Comment by skearnes** [comment]
@marcosfelt I'm closing this due to inactivity.

**Pull request closed without merging**
