### PR TITLE
Uploading Dataset for https://doi.org/10.1039/C5SC04751J Partial Figure 4

### PR DESCRIPTION
**Pull request by mwleklin**
This dataset was prepared using the online editor. It is a partial data from figure 4 in the paper entries 11-15, representing 90 reactions.
[Submission.zip](https://github.com/open-reaction-database/ord-data/files/6584654/Submission.zip)

### CODE REVIEW

**Comment by skearnes** [comment]
Hi @mwleklin, I see 50 deleted files and no new files in this PR?

**Comment by mwleklin** [comment]
I see my mistake I accidentally pulled the wrong fork. Can I update this pull request to a different fork? Or would it be better for me to update my fork to current version and resubmit pull request?

**Comment by skearnes** [comment]
> I see my mistake I accidentally pulled the wrong fork. Can I update this pull request to a different fork? Or would it be better for me to update my fork to current version and resubmit pull request?

Either way; whatever fork you merge into your local `main` branch will be the one that shows up here.

**Comment by mwleklin** [comment]
Let's close this pull request out and let me start a new one. Whatever I did a while back didn't allow me to create a update my fork of ord-data to the original one (even through command line). So I ended up having to make a new fork, apologies for the issues, never sure where the issue is originating from.

**Pull request closed without merging**
