### PR TITLE
Nanomole flow resubmission

### PR DESCRIPTION
**Pull request by mwleklin**
This dataset was prepared using the interactive editor and enumerated using command line. The set was validated using the validation script. 

[Resubmission.zip](https://github.com/open-reaction-database/ord-data/files/6064036/Resubmission.zip)

image

### CODE REVIEW

**Comment by skearnes** [comment]
Thanks Mike! Could you please revert your deletion of the `data/` directory? Your fork is likely out of date since we've added a lot of datasets recently.

**Comment by mwleklin** [comment]
> Thanks Mike! Could you please revert your deletion of the `data/` directory? Your fork is likely out of date since we've added a lot of datasets recently.

Yes, not realizing how the clone works, I deleted that file in order to clone to my desktop. I get the following error when trying to download that data, any suggestions?

image

**Comment by skearnes** [comment]
Do you have git LFS installed?
https://github.com/Open-Reaction-Database/ord-data#cloning-with-git-lfs

**Comment by skearnes** [comment]
I've never seen an error like that before; could be a firewall issue. You might try removing Git LFS and re-cloning (you shouldn't need it to submit). Then you won't be accessing files hosted off github...

**Comment by skearnes** [comment]
Maybe try this: https://stackoverflow.com/a/42021818

**Comment by mwleklin** [comment]
Thanks, that made the clone work. I think I have the resubmission correctly now?

**Comment by skearnes** [comment]
Thanks Mike! Validations look good, and I'll let @michaelmaser confirm the edits.

**Review by michaelmaser — APPROVED** [review]
Looks great. Parsing and validations all working well. Thanks Mike!

**Pull request merged**
