### PR TITLE
Bump ord-schema version

### PR DESCRIPTION
**Pull request by skearnes**
| Dataset ID | Name | Owner | Status |
| - | - | - | - |
| `ord_dataset-33320f511ffb4f89905448c7a5153111` | Nanomole flow | @skearnes | x |
| `ord_dataset-46ff9a32d9e04016b9380b1b1ef949c3` | Ahneman | @connorcoley | x |
| `ord_dataset-7d8f5fd922d4497d91cb81489b052746` | Santanilla | @michaelmaser | x |
| `ord_dataset-b440f8c90b6343189093770060fc4098` | Photodehalogenation | @skearnes | x |
| `ord_dataset-cbcc4048add7468e850b6ec42549c70d` | Merck CN cross coupling | @connorcoley | x |
| `ord_dataset-d319c2a22ecf4ce59db1a18ae71d529c` | Suzuki informer | @michaelmaser | x |

### CODE REVIEW

**Comment by skearnes** [comment]
FYI added a table of the datasets needing migration so we can claim them.

**Comment by michaelmaser** [comment]
Could you give a quick blurb on your workflow for this, please? Want to make sure I'm catching everything.

**Comment by skearnes** [comment]
> Could you give a quick blurb on your workflow for this, please? Want to make sure I'm catching everything.

Sure. For the photodehalogenation dataset I looked at the template pbtxt and saw that I didn't need to change anything for the products, since the results were reported as `conversion`. So then I just ran @connorcoley's migration script (https://github.com/open-reaction-database/ord-schema/pull/522) after updating the script to make sure the `record_modified` data matched me.

I think for more complicated edits I'll have to update the template manually, re-enumerate the dataset, and then programmatically copy over the existing reaction IDs, provenance info, etc.

**Comment by skearnes** [comment]
PS the migration script seemed to be all that was needed for `ord_dataset-33320f511ffb4f89905448c7a5153111` as well.

**Comment by skearnes** [comment]
(nit: the `record_modified` details should indicate v0.2.3, not v0.2.2)

**Comment by michaelmaser** [comment]
Migration script seemed to work great for `ord_dataset-d319c2a22ecf4ce59db1a18ae71d529c`. 

I'm thinking the final dataset (Santanilla HTE) will be more complicated. Since I generated the pbtxt programmatically and I've updated the notebook with schema modifications (mostly), I'm thinking of just regenerating the pbtxt with reaction_id's copied over and updated provenance. Can then run the migration script afterwards to make sure. @skearnes @connorcoley thoughts?

**Comment by connorcoley** [comment]
> I'm thinking the final dataset (Santanilla HTE) will be more complicated. Since I generated the pbtxt programmatically and I've updated the notebook with schema modifications (mostly), I'm thinking of just regenerating the pbtxt with reaction_id's copied over and updated provenance. Can then run the migration script afterwards to make sure. @skearnes @connorcoley thoughts?

I think that's a great idea. Otherwise, you'd need a very custom, dataset-specific migration script.

**Comment by michaelmaser** [comment]
Update: Manual/programmatic editing and re-writing of the pbtxt complete and working. However, the migration script is failing on the re-generated pbtxt since the fields are already in the new schema format. Example error:

`ValueError: error parsing data/7d/ord_dataset-7d8f5fd922d4497d91cb81489b052746.pbtxt: 20:9 : Message type "ord_old.Compound" has no field named "amount".`

@skearnes @connorcoley thoughts on course of action? Could just replace the old pbtxt with this new one since it was generated with the new schema version anyway, and thus could be considered "migrated". 

Copy-over of `reaction_id`'s, `dataset_id`, and all `provenance` info (original `record_created` and new `record_modified`) seems to be successful on a couple of visual checks, though would want you to take a look. Made all the migration modifications in the `example_Santanilla.ipynb` in a `migration` branch on my fork of `ord-schema`.

**Comment by connorcoley** [comment]
> Could just replace the old pbtxt with this new one since it was generated with the new schema version anyway, and thus could be considered "migrated".

Yes, that's what I thought you had in mind. I don't think we need to rely on the migration script at all for this example. If you're preserving the reaction_ids and dataset_id, then I think we should be all set

**Comment by michaelmaser** [comment]
> Yes, that's what I thought you had in mind. I don't think we need to rely on the migration script at all for this example. If you're preserving the reaction_ids and dataset_id, then I think we should be all set

Great, thanks. Done!

**Comment by skearnes** [comment]
Thanks everyone! `process_dataset` is failing because the `main` branch is using a different schema version. However, a look at the [logs](https://github.com/open-reaction-database/ord-data/runs/1589533717) shows that the validations are passing for all six datasets.

Let's get everyone's approval and then merge.

**Comment by skearnes** [comment]
I'll suggest that @connorcoley approve for Mike's datasets, @michaelmaser approve for mine, and I'll approve for Connor's. Just to make sure we're not losing any information.

**Comment by skearnes** [comment]
@connorcoley can you comment on your note that "the original dataset contains information that might be slightly richer" in https://github.com/open-reaction-database/ord-data/pull/43/commits/48f0a76256108b57781a405f884a66c36d7d46f7? AFAICT there was no loss of information in the migration?

**Comment by skearnes** [comment]
@michaelmaser please add a new `record_modified` entry on the Santanilla dataset instead of overwriting the existing one.

**Comment by michaelmaser** [comment]
> @michaelmaser please add a new `record_modified` entry on the Santanilla dataset instead of overwriting the existing one.

Are you referring to the `record_modified` from "github-actions"?

**Comment by skearnes** [comment]
> > @michaelmaser please add a new `record_modified` entry on the Santanilla dataset instead of overwriting the existing one.
> 
> Are you referring to the `record_modified` from "github-actions"?

Yes.

**Review by michaelmaser — APPROVED** [review]
@skearnes datasets look good to me. 

General comment that products in photodehalogenation dataset (b4) do not have `is_desired_product` set, and both datasets (b4 & 33) do not have products' `reaction_role=PRODUCT`. See that this was true of former version(s) as well. Do we plan to add these later or leave as entered?

**Comment by skearnes** [comment]
> @skearnes datasets look good to me.
> 
> General comment that products in photodehalogenation dataset (b4) do not have `is_desired_product` set, and both datasets (b4 & 33) do not have products' `reaction_role=PRODUCT`. See that this was true of former version(s) as well. Do we plan to add these later or leave as entered?

I'm generally in favor of just making this PR about migration and not cleanup, but happy to add these if you think we should just take care of it now. WDYT?

**Comment by michaelmaser** [comment]
> I'm generally in favor of just making this PR about migration and not cleanup, but happy to add these if you think we should just take care of it now. WDYT?

Agreed. Was just curious

**Comment by connorcoley** [comment]
> I'm generally in favor of just making this PR about migration and not cleanup, but happy to add these if you think we should just take care of it now. WDYT?

Agreed. Let's merge

**Pull request merged**
